# Generated by Django 5.2.7 on 2025-10-19 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('stuClass', models.TextField()),
                ('gender', models.CharField(max_length=50)),
                ('activities', models.TextField(blank=True)),
                ('myImage', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/')),
            ],
        ),
    ]
