# Generated by Django 5.2.7 on 2025-10-27 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Submission',
        ),
    ]
